{
 "title": "chat-application",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage Percentage | Disk Usage Percentage",
   "type": "gauge",
   "description": "CPU usage percentage \nDisk usage percentage",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_usage_percent", "legendFormat": "__auto" },
    { "expr": "disk_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP Total Request | Total Number of Active Connections | Total number of WS Connections",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{instance=\"backend:8000\", job=\"backend\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ws_connections_active{instance=\"backend:8000\", job=\"backend\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ws_total_connections_total{instance=\"backend:8000\", job=\"backend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage MB",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 8 },
   "targets": [
    { "expr": "memory_usage_mb", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage Percentage | Number of OS threads created",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cpu_usage_percent{job=\"backend\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "go_threads{job=\"prometheus\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_cpu_seconds_total{instance=\"backend:8000\", job=\"backend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WS Active Connection | Total Disconnection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "ws_connections_active{instance=\"backend:8000\", job=\"backend\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ws_disconnections_total{instance=\"backend:8000\", job=\"backend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WS Total Message Received | Sent | Overall Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ws_messages_received_total{instance=\"backend:8000\", job=\"backend\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ws_messages_sent_total{instance=\"backend:8000\", job=\"backend\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ws_messages_total{instance=\"backend:8000\", job=\"backend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WS DB Total Queries | Redis Total Queries | Redis Total Connections  ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "ws_database_queries_total{instance=\"backend:8000\", job=\"backend\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "redis_queries_total{instance=\"backend:8000\", job=\"backend\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "redis_channels_created_total{instance=\"backend:8000\", job=\"backend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Root Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{logger=\"root\"} |= ``"
    }
   ]
  }
 ]
}