global:
  scrape_interval: 10s  # Adjust scrape frequency

scrape_configs:
  - job_name: "backend"
    static_configs:
      - targets: ["backend:8000"]

  - job_name: "celery_worker"
    static_configs:
      - targets: ["celery_worker:8000"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
