version: '3.8'

networks:
  chat-application_my-networks:
    external: true  

services:
  locust:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: locust_tester
    volumes:
      - .:/mnt/locust
    # ulimits:
    #   nofile:
    #     soft: 65535
    #     hard: 65535
    working_dir: /mnt/locust
    command: >
      locust -f locustfile.py --headless -u 2000 -r 20 --host ws://backend:8000
    networks:
      - chat-application_my-networks
    # depends_on:
    #   - fastapi